title: Solid Community
author: 
  name: Stichting Solid Community
  email: info@solidcommunity.nl

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: Samenwerken aan een vriendelijker veiliger web
locale: nl

# Build settings

theme: minima
kramdown:
  input: Kramdown

collections:
  pages:
    output: true
    permalink: /:path
  
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"
  # Generate social links in footer.
  #
  # social_links:

  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #   - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
# - En_index.md
- toepassingen.md
- samenwerken.md
- aanpak.md
- blog.md
- over.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
